// Generated by Tools/generate-compatibility.py. Do not edit.
namespace VRVlog.LilToonExporter.Compatibility
{
    public static partial class DependencyPolicy
    {
        public const string LilToonVersion = "2.3.4";
        public const string LilToonCommit = "252fd8cfc46106d4967e95b3f2c788418502f227";
        public const string UniVrmAdapter = "univrm-0.131";
        public const string UniVrmVersions = "0.131.0, 0.131.1, 0.131.2";
        public const string NdmfMinimum = "1.8.3";
        public const string NdmfReference = "1.14.8";
        public const string ModularAvatarReference = "1.18.7";
        public const int NdmfMajor = 1;
        public static bool SupportsUniVrm(string version) =>
            version == "0.131.0" || version == "0.131.1" || version == "0.131.2";
    }
}
