using System;
using System.Linq;
using System.Threading.Tasks;
using NUnit.Framework;
using UniGLTF;
using UniVRM10;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;
using Object = UnityEngine.Object;

namespace VRVlog.LilToonExporter.Tests
{
    // Uses the installed MA/NDMF processor, with no replacement test bridge.
    // Covers renderer hierarchy relocation/replacement and retargeted FX curves;
    // the morph geometry is authored beforehand, not generated by a plugin.
    public sealed class InstalledNdmfNeutralExportTests
    {
        static Type InstalledType(string name) => AppDomain.CurrentDomain.GetAssemblies()
            .Select(assembly => assembly.GetType(name)).FirstOrDefault(type => type != null);

        static void SetFx(Component descriptor, RuntimeAnimatorController controller)
        {
            using var data = new SerializedObject(descriptor);
            data.FindProperty("customizeAnimationLayers").boolValue = true;
            var layers = data.FindProperty("baseAnimationLayers"); layers.arraySize = 1;
            var layer = layers.GetArrayElementAtIndex(0);
            var type = layer.FindPropertyRelative("type"); type.enumValueIndex = Array.IndexOf(type.enumNames, "FX");
            layer.FindPropertyRelative("isDefault").boolValue = false;
            layer.FindPropertyRelative("animatorController").objectReferenceValue = controller;
            data.ApplyModifiedPropertiesWithoutUndo();
        }

        static AnimatorController DefaultController(string asset, AnimationClip clip = null)
        {
            var controller = AnimatorController.CreateAnimatorControllerAtPath(asset);
            if (clip != null) AssetDatabase.AddObjectToAsset(clip, controller);
            var machine = controller.layers[0].stateMachine;
            var state = machine.AddState("Neutral"); state.writeDefaultValues = false; state.motion = clip;
            machine.defaultState = state;
            return controller;
        }

        static Vector3[] NativeWorldVertices(SkinnedMeshRenderer renderer, float? weight = null)
        {
            var original = renderer.GetBlendShapeWeight(0);
            var baked = new Mesh();
            try
            {
                if (weight.HasValue) renderer.SetBlendShapeWeight(0, weight.Value);
                renderer.BakeMesh(baked);
                return baked.vertices.Select(renderer.transform.TransformPoint).ToArray();
            }
            finally
            {
                renderer.SetBlendShapeWeight(0, original);
                Object.DestroyImmediate(baked);
            }
        }

        static void AssertVertices(Vector3[] actual, Vector3[] expected, string message)
        {
            Assert.That(actual.Length, Is.EqualTo(expected.Length), message);
            for (var i = 0; i < expected.Length; i++)
                Assert.That(Vector3.Distance(actual[i], expected[i]), Is.LessThan(.0001f), message + " vertex " + i);
        }

        [Test]
        public void InstalledModularAvatarProcessesAnInactiveMergeAnimatorForPreparedFx()
        {
            var descriptorType = InstalledType("VRC.SDK3.Avatars.Components.VRCAvatarDescriptor");
            var mergeType = InstalledType("nadena.dev.modular_avatar.core.ModularAvatarMergeAnimator");
            if (descriptorType == null || mergeType == null)
                Assert.Ignore("Install the real VRChat SDK, Modular Avatar and NDMF for inactive FX authoring.");
            using var fixture = new AttachmentConnectionTests.Fixture();
            var folderName = "__InstalledInactiveMa_" + Guid.NewGuid().ToString("N");
            AssetDatabase.CreateFolder("Assets", folderName);
            var folder = "Assets/" + folderName;
            try
            {
                fixture.Mesh.ClearBlendShapes();
                fixture.Mesh.AddBlendShapeFrame("Opening", 100,
                    Enumerable.Repeat(Vector3.up * .03f, fixture.Mesh.vertexCount).ToArray(), null, null);
                var sourceFront = fixture.Source.transform.Find("Front").GetComponent<SkinnedMeshRenderer>();
                var sourceWeight = sourceFront.GetBlendShapeWeight(0);
                SetFx(fixture.Source.AddComponent(descriptorType), DefaultController(folder + "/Base.controller"));
                var clip = new AnimationClip { name = "Inactive MA facial FX" };
                var binding = EditorCurveBinding.FloatCurve("Front", typeof(SkinnedMeshRenderer), "blendShape.Opening");
                AnimationUtility.SetEditorCurve(clip, binding, AnimationCurve.Constant(0, 1, 75));
                var controller = DefaultController(folder + "/Inactive.controller", clip);
                var setting = new GameObject("Inactive FX authoring");
                setting.transform.SetParent(fixture.Source.transform, false);
                setting.SetActive(false);
                var merge = setting.AddComponent(mergeType);
                mergeType.GetField("animator").SetValue(merge, controller);
                var pathMode = mergeType.GetField("pathMode");
                pathMode.SetValue(merge, Enum.Parse(pathMode.FieldType, "Absolute"));
                var sourceSettings = EditorJsonUtility.ToJson(merge);
                Object.DestroyImmediate(fixture.Copy);
                fixture.Copy = Object.Instantiate(fixture.Source);

                using (NdmfExportPreparation.Prepare(fixture.Source, fixture.Copy))
                {
                    Assert.That(NeutralShapeSampler.Sample(fixture.Copy)
                        .Single(value => value.Path == "Front" && value.Shape == "Opening").Weight,
                        Is.EqualTo(75), "Inactive MA authoring must participate in its canonical FX merge.");
                    Assert.That(fixture.Copy.GetComponentsInChildren<Component>(true)
                        .Any(component => component != null && component.GetType() == mergeType), Is.False);
                    Assert.That(setting.activeSelf, Is.False);
                    Assert.That(setting.GetComponent(mergeType), Is.SameAs(merge));
                    Assert.That(EditorJsonUtility.ToJson(merge), Is.EqualTo(sourceSettings));
                    Assert.That(AnimationUtility.GetEditorCurve(clip, binding).Evaluate(0), Is.EqualTo(75));
                    Assert.That(sourceFront.GetBlendShapeWeight(0), Is.EqualTo(sourceWeight),
                        "Canonical preparation must preserve the source's authored neutral weight.");
                }
            }
            finally { AssetDatabase.DeleteAsset(folder); }
        }

        [TestCase(false)]
        [TestCase(true)]
        public async Task InstalledModularAvatarRetargetsMovedRendererDefaultFxAndAuthoredEndpointInRealVrm(bool fullLilToon)
        {
            var descriptorType = InstalledType("VRC.SDK3.Avatars.Components.VRCAvatarDescriptor");
            var mergeType = InstalledType("nadena.dev.modular_avatar.core.ModularAvatarMergeAnimator");
            var proxyType = InstalledType("nadena.dev.modular_avatar.core.ModularAvatarBoneProxy");
            if (descriptorType == null || mergeType == null || proxyType == null)
                Assert.Ignore("Install the real VRChat SDK, Modular Avatar and NDMF to run their real processing pipeline.");

            using var fixture = new AttachmentConnectionTests.Fixture();
            var folderName = "__InstalledNdmfNeutral_" + Guid.NewGuid().ToString("N");
            AssetDatabase.CreateFolder("Assets", folderName); var folder = "Assets/" + folderName;
            var vrm = ScriptableObject.CreateInstance<VRM10Object>();
            var expression = ScriptableObject.CreateInstance<VRM10Expression>();
            Vrm10Instance imported = null;
            NdmfExportPreparation preparation = null;
            try
            {
                fixture.Mesh.ClearBlendShapes();
                fixture.Mesh.AddBlendShapeFrame("Opening", 50,
                    Enumerable.Repeat(Vector3.up * .01f, fixture.Mesh.vertexCount).ToArray(), null, null);
                fixture.Mesh.AddBlendShapeFrame("Opening", 100,
                    Enumerable.Repeat(Vector3.up * .03f, fixture.Mesh.vertexCount).ToArray(), null, null);
                foreach (var skin in fixture.Source.GetComponentsInChildren<SkinnedMeshRenderer>())
                { skin.SetBlendShapeWeight(0, 0); skin.sharedMaterial.shader = Shader.Find("lilToon"); }
                var front = fixture.Source.transform.Find("Front").GetComponent<SkinnedMeshRenderer>();
                var back = fixture.Source.transform.Find("Back").GetComponent<SkinnedMeshRenderer>();
                var expectedNeutral = NativeWorldVertices(front, 0);
                var expectedEndpoint = NativeWorldVertices(front, 25);
                var expectedBack = NativeWorldVertices(back, 0);
                var sourceVertices = fixture.Mesh.vertices;

                SetFx(fixture.Source.AddComponent(descriptorType), DefaultController(folder + "/Base.controller"));
                var clip = new AnimationClip { name = "MA relative neutral75" };
                var binding = EditorCurveBinding.FloatCurve("", typeof(SkinnedMeshRenderer), "blendShape.Opening");
                AnimationUtility.SetEditorCurve(clip, binding, AnimationCurve.Constant(0, 1, 75));
                var mergeController = DefaultController(folder + "/Relative.controller", clip);
                var merge = front.gameObject.AddComponent(mergeType);
                mergeType.GetField("animator").SetValue(merge, mergeController);
                var pathMode = mergeType.GetField("pathMode");
                pathMode.SetValue(merge, Enum.Parse(pathMode.FieldType, "Relative"));
                var proxy = front.gameObject.AddComponent(proxyType);
                proxyType.GetField("boneReference").SetValue(proxy, HumanBodyBones.Head);
                var mode = proxyType.GetField("attachmentMode");
                mode.SetValue(proxy, Enum.Parse(mode.FieldType, "AsChildKeepWorldPose"));
                expression.name = "MA partial";
                expression.MorphTargetBindings = new[] { new MorphTargetBinding("Front", 0, .25f) };
                vrm.Expression.CustomClips.Add(expression);
                fixture.Source.AddComponent<Vrm10Instance>().Vrm = vrm;

                Object.DestroyImmediate(fixture.Copy); fixture.Copy = Object.Instantiate(fixture.Source);
                var preparedFront = fixture.Copy.transform.Find("Front").GetComponent<SkinnedMeshRenderer>();
                preparation = NdmfExportPreparation.Prepare(fixture.Source, fixture.Copy);
                var preparedHead = fixture.Copy.GetComponent<Animator>().GetBoneTransform(HumanBodyBones.Head);
                Assert.That(preparedFront.transform.parent, Is.SameAs(preparedHead), "The installed MA Bone Proxy pass must move the renderer.");
                Assert.That(fixture.Copy.transform.Find("Front"), Is.Null);
                var preparedPath = AnimationUtility.CalculateTransformPath(preparedFront.transform, fixture.Copy.transform);
                Assert.That(NeutralShapeSampler.Sample(fixture.Copy).Single(value => value.Path == preparedPath && value.Shape == "Opening").Weight,
                    Is.EqualTo(75), "The installed MA Merge Animator and NDMF path remapper must supply the moved default curve.");
                Assert.That(preparedFront.GetComponent(mergeType), Is.Null);
                Assert.That(preparedFront.GetComponent(proxyType), Is.Null);

                // Export the untouched authoring source, so the public pipeline
                // performs its own real preparation and authored-bind rebinding.
                var bytes = UniVrmOneClickExporter.Export(fixture.Source, "Installed MA neutral regression", "Tests",
                    exporterVersion: fullLilToon ? "installed-ndmf-neutral-regression" : null,
                    lilToonVersion: fullLilToon ? "2.3.4" : null,
                    blinkOptions: new BlinkExportOptions { Mode = BlinkExportMode.None });
                imported = await Vrm10.LoadBytesAsync(bytes, canLoadVrm0X: false, awaitCaller: new ImmediateCaller());
                imported.Runtime.Process();
                var output = imported.GetComponentsInChildren<SkinnedMeshRenderer>().Single(skin => skin.name == "Front");
                var outputBack = imported.GetComponentsInChildren<SkinnedMeshRenderer>().Single(skin => skin.name == "Back");
                AssertVertices(NativeWorldVertices(output), expectedNeutral, "Imported base geometry must retain prepared0 rather than restore FX75.");
                AssertVertices(NativeWorldVertices(outputBack), expectedBack, "The other renderer sharing the original mesh must stay at zero.");
                Assert.That(imported.Vrm.Expression.CustomClips.Any(value => value.name == expression.name), Is.True);
                imported.Runtime.Expression.SetWeight(ExpressionKey.CreateCustom(expression.name), 1);
                imported.Runtime.Process();
                AssertVertices(NativeWorldVertices(output), expectedEndpoint, "The moved authored0.25 endpoint must reach the source native25 pose.");
                AssertVertices(NativeWorldVertices(outputBack), expectedBack, "The moved authored endpoint must keep its renderer scope.");

                Assert.That(front.transform.parent, Is.SameAs(fixture.Source.transform));
                Assert.That(front.GetComponent(mergeType), Is.SameAs(merge));
                Assert.That(front.GetComponent(proxyType), Is.SameAs(proxy));
                Assert.That(front.sharedMesh, Is.SameAs(fixture.Mesh));
                Assert.That(back.sharedMesh, Is.SameAs(fixture.Mesh));
                Assert.That(front.GetBlendShapeWeight(0), Is.Zero);
                Assert.That(back.GetBlendShapeWeight(0), Is.Zero);
                Assert.That(fixture.Mesh.vertices, Is.EqualTo(sourceVertices));
                Assert.That(AnimationUtility.GetCurveBindings(clip).Single().path, Is.Empty);
                Assert.That(AnimationUtility.GetEditorCurve(clip, binding).Evaluate(0), Is.EqualTo(75));
                Assert.That(fixture.Source.GetComponent<Vrm10Instance>().Vrm, Is.SameAs(vrm));
                Assert.That(expression.MorphTargetBindings.Single().RelativePath, Is.EqualTo("Front"));
                Assert.That(expression.MorphTargetBindings.Single().Weight, Is.EqualTo(.25f));
            }
            finally
            {
                if (imported != null) Object.DestroyImmediate(imported.gameObject);
                preparation?.Dispose();
                Object.DestroyImmediate(expression); Object.DestroyImmediate(vrm);
                AssetDatabase.DeleteAsset(folder);
            }
        }

        [Test]
        public async Task InstalledModularAvatarReplacementUsesFinalRendererKeyForNeutralWithoutAnAuthoredRoute()
        {
            var descriptorType = InstalledType("VRC.SDK3.Avatars.Components.VRCAvatarDescriptor");
            var replaceType = InstalledType("nadena.dev.modular_avatar.core.ModularAvatarReplaceObject");
            if (descriptorType == null || replaceType == null)
                Assert.Ignore("Install the real VRChat SDK, Modular Avatar and NDMF to run their real processing pipeline.");
            using var fixture = new AttachmentConnectionTests.Fixture();
            var folderName = "__InstalledNdmfReplacement_" + Guid.NewGuid().ToString("N");
            AssetDatabase.CreateFolder("Assets", folderName); var folder = "Assets/" + folderName;
            var replacementMesh = Object.Instantiate(fixture.Mesh);
            Vrm10Instance imported = null;
            try
            {
                fixture.Mesh.ClearBlendShapes();
                fixture.Mesh.AddBlendShapeFrame("Original opening", 100,
                    Enumerable.Repeat(Vector3.up * .01f, fixture.Mesh.vertexCount).ToArray(), null, null);
                replacementMesh.ClearBlendShapes();
                replacementMesh.AddBlendShapeFrame("Prepared opening", 100,
                    Enumerable.Repeat(Vector3.up * .03f, replacementMesh.vertexCount).ToArray(), null, null);
                var original = fixture.Source.transform.Find("Front").GetComponent<SkinnedMeshRenderer>();
                var replacement = fixture.Source.transform.Find("Back").GetComponent<SkinnedMeshRenderer>();
                replacement.name = "Prepared face"; replacement.sharedMesh = replacementMesh;
                foreach (var skin in new[] { original, replacement })
                { skin.SetBlendShapeWeight(0, 0); skin.sharedMaterial.shader = Shader.Find("lilToon"); }
                var expected = NativeWorldVertices(replacement, 0);
                var clip = new AnimationClip { name = "Replacement neutral75" };
                // The geometry key exists only on the replacement renderer;
                // MA supplies the route to it during its real Transforming pass.
                var binding = EditorCurveBinding.FloatCurve("Front", typeof(SkinnedMeshRenderer), "blendShape.Prepared opening");
                AnimationUtility.SetEditorCurve(clip, binding, AnimationCurve.Constant(0, 1, 75));
                SetFx(fixture.Source.AddComponent(descriptorType), DefaultController(folder + "/FX.controller", clip));
                var replace = replacement.gameObject.AddComponent(replaceType);
                var reference = replaceType.GetField("targetObject").GetValue(replace);
                reference.GetType().GetMethod("Set", new[] { typeof(GameObject) }).Invoke(reference, new object[] { original.gameObject });

                var bytes = UniVrmOneClickExporter.Export(fixture.Source, "Installed MA replacement neutral", "Tests",
                    blinkOptions: new BlinkExportOptions { Mode = BlinkExportMode.None });
                imported = await Vrm10.LoadBytesAsync(bytes, canLoadVrm0X: false, awaitCaller: new ImmediateCaller());
                imported.Runtime.Process();
                var output = imported.GetComponentsInChildren<SkinnedMeshRenderer>().Single();
                Assert.That(output.name, Is.EqualTo("Prepared face"), "The installed MA pass must replace the old renderer.");
                Assert.That(output.sharedMesh.GetBlendShapeIndex("Prepared opening"), Is.GreaterThanOrEqualTo(0));
                AssertVertices(NativeWorldVertices(output), expected, "The replacement renderer must retain its prepared0 baseline despite its FX75 curve.");
                Assert.That(original, Is.Not.Null);
                Assert.That(original.sharedMesh, Is.SameAs(fixture.Mesh));
                Assert.That(original.GetBlendShapeWeight(0), Is.Zero);
                Assert.That(replacement.sharedMesh, Is.SameAs(replacementMesh));
                Assert.That(replacement.GetBlendShapeWeight(0), Is.Zero);
                Assert.That(replacement.GetComponent(replaceType), Is.SameAs(replace));
                Assert.That(AnimationUtility.GetCurveBindings(clip).Single().path, Is.EqualTo("Front"));
                Assert.That(fixture.Source.GetComponent<Vrm10Instance>(), Is.Null);
            }
            finally
            {
                if (imported != null) Object.DestroyImmediate(imported.gameObject);
                Object.DestroyImmediate(replacementMesh);
                AssetDatabase.DeleteAsset(folder);
            }
        }
    }
}
