"""Generate the dependency policy and conditional assembly gates from one manifest."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def outputs(root=ROOT):
    data = json.loads((root / 'Compatibility/dependencies.json').read_text(encoding='utf-8'))
    assert data['format'] == 1
    vrm = data['uniVrm']
    versions = list(vrm['versions'])
    assert versions and len(versions) == len(set(versions))
    for version, commit in vrm['versions'].items():
        assert re.fullmatch(r'0\.131\.\d+', version)
        assert re.fullmatch(r'[a-f0-9]{40}', commit)
    assert vrm['releaseVersion'] in versions
    lil = data['lilToon']
    # The on-disk format and renderer stay unchanged in this compatibility update.
    assert lil['version'] == '2.3.4' and (lil['schemaMajor'], lil['schemaMinor']) == (2, 0)
    assert re.fullmatch(r'[a-f0-9]{40}', lil['commit'])
    catalogue = (root / 'Editor/LilToon234Catalogue.cs').read_text(encoding='utf-8')
    assert 'Version = "' + lil['version'] + '"' in catalogue
    assert 'Commit = "' + lil['commit'] + '"' in catalogue
    authoring = data['authoring']
    values = {
        'LilToonVersion': lil['version'], 'LilToonCommit': lil['commit'],
        'UniVrmAdapter': vrm['adapter'], 'UniVrmVersions': ', '.join(versions),
        'NdmfMinimum': authoring['ndmfMinimum'], 'NdmfReference': authoring['ndmfReference'],
        'ModularAvatarReference': authoring['modularAvatarReference'],
    }
    text = '// Generated by Tools/generate-compatibility.py. Do not edit.\n'
    text += 'namespace VRVlog.LilToonExporter.Compatibility\n{\n    public static partial class DependencyPolicy\n    {\n'
    for key, value in values.items():
        text += '        public const string ' + key + ' = ' + json.dumps(value) + ';\n'
    text += '        public const int NdmfMajor = ' + str(authoring['ndmfMajor']) + ';\n'
    text += '        public static bool SupportsUniVrm(string version) =>\n            '
    text += ' || '.join('version == ' + json.dumps(v) for v in versions) + ';\n'
    text += '    }\n}\n'
    result = {'Editor/Compatibility/DependencyPolicy.Generated.cs': text}
    definitions = []
    constraints = []
    for package, prefix in [('com.vrmc.vrm', 'VRVLOG_VRM'), ('com.vrmc.gltf', 'VRVLOG_GLTF')]:
        symbols = []
        for version in versions:
            symbol = prefix + '_' + version.replace('.', '_')
            symbols.append(symbol)
            definitions.append({'name': package, 'expression': '[' + version + ']', 'define': symbol})
        constraints.append(' || '.join(symbols))
    for name in ['Editor/VRVlog.LilToonExporter.Editor.asmdef', 'Tests/Editor/VRVlog.LilToonExporter.Editor.Tests.asmdef']:
        asm = json.loads((root / name).read_text(encoding='utf-8'))
        asm['defineConstraints'] = constraints
        asm['versionDefines'] = definitions
        if name.startswith('Editor/') and 'VRVlog.LilToonExporter.Compatibility' not in asm['references']:
            asm['references'].append('VRVlog.LilToonExporter.Compatibility')
        result[name] = json.dumps(asm, indent=2) + '\n'
    package_path = root / 'package.json'
    package = json.loads(package_path.read_text(encoding='utf-8'))
    for name in ['com.vrmc.gltf', 'com.vrmc.vrm']:
        package['vpmDependencies'][name] = vrm['vpmRange']
    result['package.json'] = json.dumps(package, indent=2, ensure_ascii=False) + '\n'
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    stale = []
    for name, content in outputs().items():
        path = ROOT / name
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8', newline='\n')
        elif not path.exists() or path.read_text(encoding='utf-8') != content:
            stale.append(name)
    if stale:
        raise SystemExit('Run python3 Tools/generate-compatibility.py --write: ' + ', '.join(stale))
    print('Dependency policy and assembly gates match the compatibility manifest.')


if __name__ == '__main__':
    main()
