name: Build VPM Listing

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches: [main]
    paths: [source.json, Website/**, .github/workflows/build-listing.yml]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

env:
  listPublishDirectory: Website
  pathToCi: ci

jobs:
  build-listing:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: vrchat-community/package-list-action
          ref: cb31c3b5d17d1070d7741c61de2ca1b219224039
          path: ${{ env.pathToCi }}
          clean: false
      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build package listing
        run: |
          dotnet build ${{ env.pathToCi }}/PackageBuilder/PackageBuilder.csproj \
            --framework net8.0 \
            --disable-build-servers \
            --maxcpucount:1 \
            /nodeReuse:false \
            /p:UseSharedCompilation=false \
            --nologo
          dotnet run \
            --project ${{ env.pathToCi }}/PackageBuilder/PackageBuilder.csproj \
            --no-build \
            --framework net8.0 \
            -- \
            BuildMultiPackageListing \
            --root ${{ env.pathToCi }} \
            --list-publish-directory $GITHUB_WORKSPACE/${{ env.listPublishDirectory }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.listPublishDirectory }}
      - id: deployment
        uses: actions/deploy-pages@v4
